/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package group.Interfaces;

import group.Physics.PhysicsObject;
import group.Physics.PhysicsOperator;

/**
 *
 * @author lizandro
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    PhysicsObject object = new PhysicsObject();
    public MainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        VectorlessTab = new javax.swing.JTabbedPane();
        Operaciones = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        TimeField = new javax.swing.JTextField();
        SpeedField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DistanceField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AccelerationField = new javax.swing.JTextField();
        ForceField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        MassField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        FinalAccField = new javax.swing.JTextField();
        InitialAccField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        InitialSpeedField = new javax.swing.JTextField();
        FinalSpeedField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        HeightField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        WeightField = new javax.swing.JTextField();
        MomentumField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        RefillAllButton = new javax.swing.JButton();
        ValuesToZero = new javax.swing.JButton();
        VectorTab = new javax.swing.JTabbedPane();
        EntidadesBasicasDocumentacion = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        VectoresDocumentacion = new javax.swing.JPanel();

        jTextField1.setText("jTextField1");

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(231, 246, 255));

        TimeField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TimeField.setText("0");
        TimeField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TimeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeFieldActionPerformed(evt);
            }
        });

        SpeedField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        SpeedField.setText("0");
        SpeedField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        SpeedField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                SpeedFieldFocusLost(evt);
            }
        });
        SpeedField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                SpeedFieldPropertyChange(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Velocidad Promedio");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Tiempo");

        DistanceField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        DistanceField.setText("0");
        DistanceField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        DistanceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistanceFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Altura");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("Aceleracion promedio");

        AccelerationField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        AccelerationField.setText("0");
        AccelerationField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        ForceField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ForceField.setText("0");
        ForceField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ForceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForceFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("Fuerza");

        MassField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        MassField.setText("0");
        MassField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MassField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                MassFieldFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setText("Masa");

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel10.setText("Aceleracion Inicial");

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel11.setText("Aceleracion Final");

        FinalAccField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        FinalAccField.setText("0");
        FinalAccField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        FinalAccField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalAccFieldActionPerformed(evt);
            }
        });

        InitialAccField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        InitialAccField.setText("0");
        InitialAccField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        InitialAccField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InitialAccFieldActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel12.setText("Velocidad Inicial");

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel13.setText("Velocidad Final");

        InitialSpeedField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        InitialSpeedField.setText("0");
        InitialSpeedField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        InitialSpeedField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                InitialSpeedFieldPropertyChange(evt);
            }
        });

        FinalSpeedField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        FinalSpeedField.setText("0");
        FinalSpeedField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        FinalSpeedField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                FinalSpeedFieldPropertyChange(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel14.setText("Distancia");

        HeightField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        HeightField.setText("0");
        HeightField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        HeightField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeightFieldActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel15.setText("Peso");

        WeightField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        WeightField.setText("0");
        WeightField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        WeightField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                WeightFieldFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SpeedField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ForceField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DistanceField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MassField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(InitialSpeedField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FinalSpeedField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FinalAccField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(InitialAccField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(AccelerationField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HeightField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(WeightField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpeedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(InitialSpeedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(FinalSpeedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DistanceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(HeightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(AccelerationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InitialAccField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FinalAccField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ForceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(MassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(WeightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MomentumField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        MomentumField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        jLabel7.setText("Momentum");

        RefillAllButton.setBackground(new java.awt.Color(120, 187, 255));
        RefillAllButton.setText("Press Me!");
        RefillAllButton.setBorder(null);
        RefillAllButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RefillAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefillAllButtonActionPerformed(evt);
            }
        });

        ValuesToZero.setBackground(new java.awt.Color(158, 200, 243));
        ValuesToZero.setText("All To Zero");
        ValuesToZero.setBorder(null);
        ValuesToZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValuesToZeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OperacionesLayout = new javax.swing.GroupLayout(Operaciones);
        Operaciones.setLayout(OperacionesLayout);
        OperacionesLayout.setHorizontalGroup(
            OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RefillAllButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(OperacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OperacionesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(MomentumField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(OperacionesLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(ValuesToZero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        OperacionesLayout.setVerticalGroup(
            OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperacionesLayout.createSequentialGroup()
                .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OperacionesLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(97, 97, 97)
                        .addComponent(MomentumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RefillAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ValuesToZero)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        VectorlessTab.addTab("Physics Operations", Operaciones);
        VectorlessTab.addTab("Vectors", VectorTab);

        jLabel8.setText("Fuerza = Masa x Aceleracion");

        jLabel9.setText("Distancia = Velocidad x Tiempo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addContainerGap(605, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(361, Short.MAX_VALUE))
        );

        EntidadesBasicasDocumentacion.addTab("Formulas", jPanel1);

        javax.swing.GroupLayout VectoresDocumentacionLayout = new javax.swing.GroupLayout(VectoresDocumentacion);
        VectoresDocumentacion.setLayout(VectoresDocumentacionLayout);
        VectoresDocumentacionLayout.setHorizontalGroup(
            VectoresDocumentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 816, Short.MAX_VALUE)
        );
        VectoresDocumentacionLayout.setVerticalGroup(
            VectoresDocumentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        EntidadesBasicasDocumentacion.addTab("Vectores", VectoresDocumentacion);

        VectorlessTab.addTab("Documentation", EntidadesBasicasDocumentacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VectorlessTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VectorlessTab)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ForceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ForceFieldActionPerformed

    private void DistanceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistanceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DistanceFieldActionPerformed

    private void TimeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimeFieldActionPerformed

    private void SpeedFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_SpeedFieldPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SpeedFieldPropertyChange

    private void FinalAccFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalAccFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinalAccFieldActionPerformed

    private void InitialAccFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InitialAccFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InitialAccFieldActionPerformed

    private void InitialSpeedFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_InitialSpeedFieldPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_InitialSpeedFieldPropertyChange

    private void FinalSpeedFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_FinalSpeedFieldPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_FinalSpeedFieldPropertyChange

    private void HeightFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeightFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HeightFieldActionPerformed

    private void MassFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MassFieldFocusLost
        // TODO add your handling code here:
        float val1 = Float.valueOf(SpeedField.getText());
        float val2 = Float.valueOf(MassField.getText());
        
        float valres = val1 * val2;
        MomentumField.setText(String.valueOf(valres));
    }//GEN-LAST:event_MassFieldFocusLost

    private void SpeedFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SpeedFieldFocusLost
        // TODO add your handling code here:
        float val1 = Float.valueOf(SpeedField.getText());
        float val2 = Float.valueOf(MassField.getText());
        
        float valres = val1 * val2;
        MomentumField.setText(String.valueOf(valres));
    }//GEN-LAST:event_SpeedFieldFocusLost

    private void RefillAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefillAllButtonActionPerformed
        // TODO add your handling code here:
        float distance = Float.valueOf(DistanceField.getText());
        float height = Float.valueOf(HeightField.getText());
        float time = Float.valueOf(TimeField.getText());
        
        float initSpeed = Float.valueOf(InitialSpeedField.getText());
        float finalSpeed = Float.valueOf(FinalSpeedField.getText());
        float speed = Float.valueOf(SpeedField.getText());
        
        float gravity = Float.valueOf(9.8f);
        
        float initAcc = Float.valueOf(InitialAccField.getText());
        float finalAcc = Float.valueOf(FinalAccField.getText());
        float acc = Float.valueOf(AccelerationField.getText());
        
        float mass =Float.valueOf(MassField.getText());
        float force = Float.valueOf(ForceField.getText());
        float weight = Float.valueOf(WeightField.getText());
        
        float momentum = Float.valueOf(speed*mass);
        

        
        object.setValues(distance, height, time, initSpeed, finalSpeed, speed, gravity, initAcc, finalAcc, acc, mass, force, weight, momentum);
        
        DistanceField.setText(String.valueOf(object.getDistance()));
        HeightField.setText(String.valueOf(object.getHeight()));
        TimeField.setText(String.valueOf(object.getTime()));
        
        InitialSpeedField.setText(String.valueOf(object.getInitialSpeed()));
        FinalSpeedField.setText(String.valueOf(object.getFinalSpeed()));
        SpeedField.setText(String.valueOf(object.getAverageSpeed()));
        
        InitialAccField.setText(String.valueOf(object.getInitialAcceleration()));
        FinalAccField.setText(String.valueOf(object.getFinalAcceleration()));
        AccelerationField.setText(String.valueOf(object.getAvrgAcceleration()));
        
        MassField.setText(String.valueOf(object.getMass()));
        ForceField.setText(String.valueOf(object.getForce()));
        WeightField.setText(String.valueOf(object.getWeight()));
    }//GEN-LAST:event_RefillAllButtonActionPerformed

    private void WeightFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_WeightFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_WeightFieldFocusLost

    private void ValuesToZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValuesToZeroActionPerformed
        // TODO add your handling code here:
        DistanceField.setText("0");
        HeightField.setText("0");
        TimeField.setText("0");
        
        InitialSpeedField.setText("0");
        FinalSpeedField.setText("0");
        SpeedField.setText("0");
        
        InitialAccField.setText("0");
        FinalAccField.setText("0");
        AccelerationField.setText("0");
        
        MassField.setText("0");
        ForceField.setText("0");
        WeightField.setText("0");
        MomentumField.setText("0");
    }//GEN-LAST:event_ValuesToZeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccelerationField;
    private javax.swing.JTextField DistanceField;
    private javax.swing.JTabbedPane EntidadesBasicasDocumentacion;
    private javax.swing.JTextField FinalAccField;
    private javax.swing.JTextField FinalSpeedField;
    private javax.swing.JTextField ForceField;
    private javax.swing.JTextField HeightField;
    private javax.swing.JTextField InitialAccField;
    private javax.swing.JTextField InitialSpeedField;
    private javax.swing.JTextField MassField;
    private javax.swing.JTextField MomentumField;
    private javax.swing.JPanel Operaciones;
    private javax.swing.JButton RefillAllButton;
    private javax.swing.JTextField SpeedField;
    private javax.swing.JTextField TimeField;
    private javax.swing.JButton ValuesToZero;
    private javax.swing.JTabbedPane VectorTab;
    private javax.swing.JPanel VectoresDocumentacion;
    private javax.swing.JTabbedPane VectorlessTab;
    private javax.swing.JTextField WeightField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
